# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'relations',
            },
        ),
        migrations.CreateModel(
            name='TopRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'top_relations',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=26)),
                ('counts', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'words',
            },
        ),
        migrations.AddField(
            model_name='toprelations',
            name='top1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_top1', to='db.Words'),
        ),
        migrations.AddField(
            model_name='toprelations',
            name='top2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_top2', to='db.Words'),
        ),
        migrations.AddField(
            model_name='toprelations',
            name='top3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_top3', to='db.Words'),
        ),
        migrations.AddField(
            model_name='toprelations',
            name='top4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_top4', to='db.Words'),
        ),
        migrations.AddField(
            model_name='toprelations',
            name='top5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_top5', to='db.Words'),
        ),
        migrations.AddField(
            model_name='toprelations',
            name='wid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_wid', to='db.Words'),
        ),
        migrations.AddField(
            model_name='relations',
            name='next_wid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_next_wid', to='db.Words'),
        ),
        migrations.AddField(
            model_name='relations',
            name='wid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_wid', to='db.Words'),
        ),
    ]
