# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='value',
            field=models.CharField(max_length=26, unique=True),
        ),
    ]
