# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0003_auto_20180113_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularyrelation_0',
            name='vocab_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='vocabularyrelation_1',
            name='vocab_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='vocabularyrelation_2',
            name='vocab_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='vocabularyrelation_3',
            name='vocab_id',
            field=models.BigIntegerField(),
        ),
    ]
