# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0004_auto_20180114_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'ordering': ['-frequency', 'word']},
        ),
        migrations.AlterModelOptions(
            name='vocabularyrelation_0',
            options={'ordering': ['-frequency']},
        ),
        migrations.AlterModelOptions(
            name='vocabularyrelation_1',
            options={'ordering': ['-frequency']},
        ),
        migrations.AlterModelOptions(
            name='vocabularyrelation_2',
            options={'ordering': ['-frequency']},
        ),
        migrations.AlterModelOptions(
            name='vocabularyrelation_3',
            options={'ordering': ['-frequency']},
        ),
    ]
